run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  
  gosec:
    excludes:
      - G104

issues:
  exclude-dirs:
    - vendor
    - testdata
  max-issues-per-linter: 50
  max-same-issues: 3