# .golangci.yml - Relaxed configuration for development
version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  format: line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    # Essential linters only
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-dirs:
    - vendor
    - testdata
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"