# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  concurrency: 4
  go: "1.24"

output:
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104
      - G304

  staticcheck:
    checks: ["all", "-ST1000", "-ST1003"]

issues:
  exclude-dirs:
    - vendor
    - testdata
    - .git
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
  
  max-issues-per-linter: 50
  max-same-issues: 3
  fix: false