version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: true
  go: "1.24"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - errorlint
    - wrapcheck
    - exhaustive
    - tagalign
    - ireturn
    - nonamedreturns
    - varnamelen
    - nolintlint

linters-settings:
  staticcheck:
    # 原則はデフォルトで十分。スタイル系だけ弱めたいなら例:
    # checks: ["all", "-ST1000", "-ST1020", "-ST1021", "-ST1022"]
  tagliatelle:
    case:
      rules:
        json: camel   # API 仕様に合わせて固定（例）
    use-field-name: true
  lll:
    line-length: 120