run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: true
  go: "1.24"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - errorlint
    - wrapcheck
    - exhaustive
    - tagalign
    - ireturn
    - nonamedreturns
    - varnamelen
    - nolintlint

linters-settings:
  staticcheck:
    checks: ["all"]
  tagliatelle:
    case:
      rules:
        json: camel
  lll:
    line-length: 120