# Markdownlint configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# Path to configuration
extends: null

# MD003/heading-style/header-style - Heading style
MD003:
  style: "atx"

# MD004/ul-style - Unordered list style
MD004:
  style: "dash"

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 2
  start_indented: false

# MD009/no-trailing-spaces - Trailing spaces
MD009:
  br_spaces: 2
  list_item_empty_lines: false
  strict: false

# MD010/no-hard-tabs - Hard tabs
MD010:
  code_blocks: false
  spaces_per_tab: 4

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013/line-length - Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: false
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false

# MD022/blanks-around-headings/blanks-around-headers - Headings should be surrounded by blank lines
MD022:
  lines_above: 1
  lines_below: 1

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  allow_different_nesting: true
  siblings_only: false

# MD025/single-title/single-h1 - Multiple top-level headings in the same document
MD025:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026:
  punctuation: ".,;:!。，；：！"

# MD029/ol-prefix - Ordered list item prefix
MD029:
  style: "one_or_ordered"

# MD030/list-marker-space - Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# MD033/no-inline-html - Inline HTML
MD033:
  allowed_elements:
    - br
    - code
    - pre
    - img
    - details
    - summary
    - sub
    - sup

# MD035/hr-style - Horizontal rule style
MD035:
  style: "---"

# MD036/no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036:
  punctuation: ".,;:!?。，；：！？"

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041:
  level: 1
  front_matter_title: "^\\s*title\\s*[:=]"

# MD044/proper-names - Proper names should have the correct capitalization
MD044:
  names:
    - SciGo
    - GoML
    - scikit-learn
    - Go
    - Python
    - NumPy
    - TensorFlow
    - PyTorch
    - SGD
    - SVM
    - KMeans
    - RandomForest
    - API
    - JSON
    - YAML
    - CLI
    - CI/CD
    - GitHub
  code_blocks: false
  html_elements: false

# MD046/code-block-style - Code block style
MD046:
  style: "fenced"

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: true

# MD048/code-fence-style - Code fence style
MD048:
  style: "backtick"

# MD049/emphasis-style - Emphasis style should be consistent
MD049:
  style: "asterisk"

# MD050/strong-style - Strong style should be consistent
MD050:
  style: "asterisk"